stages:
  - test
  - build
  - e2e

.base: &base
  before_script:
    - npm ci
  image: node:11

# lint:
#   <<: *base
#   stage: test
#   script:
#     - npm run lint

# test:
#   <<: *base
#   stage: test
#   variables:
#     CODECOV_TOKEN: $CODECOV_TOKEN
#   script:
#     - npm run test -- --coverage
#     - npx codecov

# build:
#   <<: *base
#   stage: build
#   script:
#     - npm run build

e2e:
  image:
    name: docker/compose:1.24.0
    entrypoint: ['']
  stage: e2e
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - docker-compose -f example/docker-compose.yml run cypress
