stages:
  - build

variables:
  DOCKER_HOST: tcp://asdaddocker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

dockerinfo:
  image: docker:stable
  stage: build
  script:
    - docker info

build:
  image: node:latest
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

